name: AccessRequest
description: A request form to access the SDR shared environment. This issue requires approval from TransCelerate BioPharma before resolution.
title: "[AccessRequest]: "
labels: ["AccessRequest"]
assignees:
  - SushmitabSinha
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this access request form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: UserName
    attributes:
      label: User Name with Email ID
      description: Details for Access Request
      placeholder: Please provide full details
    validations:
      required: true
  - type: input
    id: Type_of_Access
    attributes:
      label: What type of access
      description: Type of access needed
      placeholder: Provide the details of access type
    validations:
      required: true
  - type: input
    id: Approval
    attributes:
      label: Approver needs to approve
      description: Approval needed
      placeholder: Please type approved for approving
      value: "@Migration-Sample/sdr-support"
    validations:
      required: true
