name: Story
description: Create a Story
title: "[Story]: "
labels: ["story"]
assignees:
  - SushmitabSinha
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a story!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description 
      description: Description or reference to the story that must work for this work to be considered complete
      placeholder: Please provide description
    validations:
      required: true
  - type: textarea
    id: AcceptanceCriteria
    attributes:
     label: Acceptance Criteria
     description: Write the acceptance criteria
     placeholder:  What needs to be done in scope of story
    validations:
     required: true
